### ISSUE TITLE
Mi_primer_proyecto_pd

### ISSUE THREAD

**Issue by SONIAFERNANDEZC** [Ironhack-Data-Madrid-Agosto-2021/w2-pandas-project#11]

**Comment by SONIAFERNANDEZC** [comment]
https://github.com/SONIAFERNANDEZC/Mi_primer_proyecto_pandas

**Comment by AnaAGG** [comment]
# 🐼🦈 Proyecto sharks 🐼🦈

Hola Sonia 🙋🏻‍♀️ vamos con las correcciones del primer proyecto del bootcamp 

## README

¿Qué pasó con el readme Sonia? 😔

El readme es parte esencial del proyecto, principalmente por que es lo primero que se ve de nuestro proyecto y donde debemos de ser capaces de sintetizar de una forma sencilla todo nuestro trabajo. 

Te dejo por aquí unos *tips* por si te aportan valor para los próximos readmes

- Lo ideal es empezar con el objetivo del proyecto. ¿Por qué lo estoy haciendo?
- Con que datos estoy trabajando:
  - De que va mi dataset, que datos tengo, que información me da 
  - De donde han salido los datos, en este caso poner el link a la página donde nos los podemos descargar
- Cuáles son nuestras hipótesis
- Cuál es el flujo de trabajo de trabajo que he seguido
- Cómo esta estructurado mi repositorio, que carpetas tengo y que me puedo encontrar en cada una de las carpetas
- Qué herramientas he usado para llevar a cabo mi trabajo (las librerias y sus vínculos a las documentación oficial)
 
## Estructura del repo

Poco te puedo comentar en esta parte. Tu repo solo tiene dos archivos de jupyter ...😔

Cosas que te dejo por aquí por si te aportan valor y que puedas ir añadiendo en los próximos protectos: 
- Lo primero de todo, pon nombre a los ficheros, en este caso podrías haber puesto como nombre `Cleaning` y `Visualization` algo que nos diga que van los jupyters que estamos viendo
- Falta la carpeta `src` donde tendríamos que poner el archivo `.py` con las funciones que deberías haber usado durante el proyecto.
- Bien que no se te haya pasado ningún archivo rarinchi o temporal fura del .`gitignore` 💪


## Sintaxis de código

- En algunas ocasiones repites lineas de código que son iguales una a continuación de otra. Por ejemplo, para eliminar nulos

  ```python
  #haces primer esto
  dataf.dropna(thresh=2)

  # y luego haces esto de nuevo
  dataf.dropna(axis=0, how="all", inplace=True)

  ```
- Suuper, te has creado una función, para que hubiera quedado perfecto lo tendrías que haber llevado a la carpeta src e importala en el jupyter. Si no recuerdas como hacerlo dimelo y lo vemos 😉
- Vamos con la columa de `year` que has intentado limpiar. Entiendo que lo que querías era generarte un dataset que no incluyera ciertos años. 

  Vamos a hacer un ejemplo:
  ```python
  # Imagina que solo estamos interesados en aquellos datos que se hayan recogido a partir del año 1900. 

  # NUESTRO DATAFRAME SE LLAMA DF

  df2 = df[df["Year"] > 1900] # de esta forma lo que estamos haciendo es seleccionar de nuestro dataframe original (df) solo aquellos valores de año (df["Year"]) que sean mayores de 1900 (> 1900)
  ```

- Sobre la columna de `Year`, fijate que el tipo de esa columna es *float*. Es raro que un año sea un float no?

  Lo primero que teniamos que haber hecho es convertir a *int* esa columna. 

  ¿Cómo lo podemos hacer? 

  ```python
  #usando el método astype

  df["Year"] = df["Year"].astype(int)
  ```
  [Aquí](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html) más documentación sobre este método

- En el segundo jupyter, al principio del jupyter reemplazas todos los NaN por "year"+

  ```python
  datafv = datafv.fillna('Year')
  # ¿Qué sentido tiene que hagas esto?
  ```
-En la gráfica que ploteas por año(la segunda), ¿Qué es lo que estas ploteando? que representa el eje y?

  En esta gráfica además el eje y esta todo muy superpuesto y hace que los años no se vean bien. Intenta para el futuro modificar estos detalles, por ejemplo rotanto el eje del label. 

## TODOs

- En general me ha faltado un poco de orde en el projecto, se repiten lineas de código a lo largo de todo el jupyter. Por ejemplo, si eliminamos columnas solo lo hacemos una vez. Si eliminamos nulos lo hacemos también una única vez. 

- A las gráficas habría que darles una vueltita para que sean más autoexplictivass
- El readme! Plis 🙏, es suuuper importante, ya se que soy suuuper pesada 🤣. 
-  Las funcioncitas en un archivo `.py`

Has sobrevivido al primer proyecto y lo has hecho genial!! En este proyecto hemos interiorizado como trabajar con pandas y cual es el principal proceso de limpieza de un dataset. Venga Sonia!! seguimos avanzando y peleandonos con pandas que al principio puede ser un poco doloroso 😔

![image](https://user-images.githubusercontent.com/75084991/131337914-4bcbc99c-b530-4cdf-961f-d14766419407.png)
