### ISSUE TITLE
[link] Alejandro

### ISSUE THREAD

**Issue by jalex141** [Ironhack-Data-Madrid-Agosto-2021/w2-pandas-project#2]
https://github.com/jalex141/Shark-tank.git

**Comment by AnaAGG** [comment]
# 🐼🦈 Proyecto sharks 🐼🦈

Hola Alejandro 🙋🏻‍♀️ vamos con las correcciones del primer proyecto del bootcamp 

## README

¿Qué pasó con el readme Alejandrooooo? 😔

El readme es parte esencial del proyecto, principalmente por que es lo primero que se ve de nuestro proyecto y donde debemos de ser capaces de sintetizar de una forma sencilla todo nuestro trabajo. 

Te dejo por aquí unos *tips* por si te aportan valor para los próximos readmes

- Lo ideal es empezar con el objetivo del proyecto. ¿Por qué lo estoy haciendo?
- Con que datos estoy trabajando:
  - De que va mi dataset, que datos tengo, que información me da 
  - De donde han salido los datos, en este caso poner el link a la página donde nos los podemos descargar
- Cuáles son nuestras hipótesis
- Cuál es el flujo de trabajo de trabajo que he seguido
- Cómo esta estructurado mi repositorio, que carpetas tengo y que me puedo encontrar en cada una de las carpetas
- Qué herramientas he usado para llevar a cabo mi trabajo (las librerías y sus vínculos a las documentación oficial)

## Estructura del repo

En general muy buen trabajo con la organización de tu repo, te dejo por aquí algunos comentarios sobre algunos detalles que vi, espero que te ayuden 😉

- Tienes un jupyter que esta vacío que se llama `Untitled`... Para el futuro, evitar tener ficheros vacíos o que no aportan nada a nuestro repo 😉
  
- Suuper bien que no se te haya pasado ningún archivo temporal ni ningún fichero que no deberieramos mostrar en el repo. Genial todos esos ficheros al `.gitignore`

- Para el futuro, se que puede resultar un poco rollo pero... la documentación de las funciones plis 🙏

    Te dejo por [aquí](https://www.python.org/dev/peps/pep-0257/) algo de documentación por si te aporta valor para el futuro 
- Como detalle, nos podemos crear un par de carpetas donde podemos almacenar determinados tipos de archivos: 
  - Una carpeta de `data` donde meteremos todos nuestros `.csv` o los archivos con los que hemos trabajado
  - Una carpeta de `Notebooks` dónde guardamos todos los jupyters que hemos ido creando. 

    Así tendremos nuestro repo perfectamente ordenaditoooo

- Por ponerme tiquismiquis, en el repo tienes cosas en inglés, otras en español... intenta unificarlo para próximos proyectos 🤓

- Por último, tienes dos jupyters con la misma información, el de `cleaning` y el de `principal`. 
  

## Sintaxis del código

- **JUPYTER DE LIMPIEZA**

  - Cuando haces el drop de los duplicados lo haces únicamente chequeando los duplicados para la columna de `Case_Number`

      ```python
      sh.drop_duplicates(subset=['Case_Number'],inplace=True)
      ```
      ¿Por qué lo haces así? 

      Quiero decir, ¿no puede haber dos ataques de tiburones en la misma fecha pero en distintos países por ejemplo? o ¿dos ataques en la misma fecha pero que no sea fatal y otro no?

      A la hora de eliminar duplicados o eliminar filas tenemos que pensarlo mucho antes de hacerlo ya que podemos estar perdiendo información muy útil.

  - Cuando rellenas todos los NaN con `Unknown` ¿Tiene sentido? 
    
    Por ejemplo, en la columna de `Age` no tendría más sentido reemplazar por la media/moda de las edades que tenemos en nuestro dataset?

  - Vamos con esta función `num_month`

      Lo primero de todo, enhorabuena por esta cadena de funciones que has creado para poder extraer información de una columna. Buen trabajo 🔝. Peeeero no podía ser todo bueno... 

      En la función `num_month` tienes un montón de `elif`, cuando esto nos pasa es que hay algo que debemos atomizar en nuestro código para evitar tener esas estructuras altamente repetitivas.

      En este caso puedes usar la librería `datetime` que nos va a permitir pasar de nombres a números en los meses

      ```python
      # un ejemplo aquí:
      month_name = "Jan"
      datetime_object = datetime.datetime.strptime(month_name, "%b")
      month_number = datetime_object.month
      print(month_number)
      # nos devuelve 1
      ``` 

      [Aquí](https://docs.python.org/3/library/datetime.html) algo de documentación sobre este método

- **JUPYTER DE VISUALIZACIÓN**
Esta parte del proyecto esta suuper bien Alejandro, peeero un par de detaillitos: 
  - En este jupyter me ha faltado algo mas de *history telling*, describes las gráficas pero no explicas el porqué de los resultados. 
  - Muchas de tus gráficas son similares, `countplots` con un `hue`. Lo que podrías haber hecho para no repetir todo el rato el mismo código es crearte una funcioncita para hacer este tipo de plots. Por ejemplo

    ```python
    def plot(df, col, hue):
        return sns.countplot(x=df[col], hue=df[hue])
    ```
## TODOs

- Darle una vuelta al readme plisss 🙏
- Atomizar algunas partes del código para evitar estructuras que se repitan mucho
- Interpretación de los resultados, no contarme solo que se ve en las gráficas. Cuéntame el porqué puede estar pasando eso. 


En general muy buen trabajo en este primer proyecto Alejandro 💪! Has sobrevivido al primer proyecto y lo has hecho genial!! En este proyecto hemos interiorizado cómo trabajar con pandas y cual es el principal proceso de limpieza de un dataset. 


![image](https://user-images.githubusercontent.com/75084991/130957431-75325691-e56a-4d51-879c-2d81bfd39e5b.png)
